export  const GET_GIT_USER_DETAIL="GET_GIT_USER_DETAIL"
export  const GET_GIT_USER_SUCCESS="GET_GIT_USER_SUCCESS"
export  const GET_GIT_USER_FAILURE="GET_GIT_USER_FAILURE"

export const GET_GIT_USER_REPO="GET_GIT_USER_REPO"
export const GET_GIT_USER_REPO_SUCCESS="GET_GIT_USER_REPO_SUCCESS"
export const GET_GIT_USER_REPO_FAILURE="GET_GIT_USER_REPO_FAILURE"
